apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-oes5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-oes5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-oes5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-oes5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-oes5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zlhh-tenant/rhtap-demo-app/hacbs-test-project-oes5@sha256:13a342b6a0e242d8119ba2aac3479a0131e4c092d7ae7ad000dcfbec84565bcf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
