apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oes5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zlhh-tenant/rhtap-demo-app/hacbs-test-project-oes5@sha256:13a342b6a0e242d8119ba2aac3479a0131e4c092d7ae7ad000dcfbec84565bcf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
